# 获取组织列表
query getOrganizations($admin: String) {
  organizations(admin: $admin) {
    name
    displayName
    description
    creationTimestamp
    lastHeartbeatTime
    admin
    status
    reason
    networks
    federations
  }
}

# 组织详情
query getOrganization($name: String!) {
  organization(name: $name) {
    name
    displayName
    description
    creationTimestamp
    lastHeartbeatTime
    admin
    status
    reason
    networks
    federations
    users {
      name
      isOrganizationAdmin
    }
  }
}

# 创建组织
mutation createOrganization($organization: NewOrganizationInput!) {
  organizationCreate(organization: $organization) {
    name
    displayName
    description
    creationTimestamp
    lastHeartbeatTime
    admin
    status
    reason
  }
}

# 更新组织
mutation updateOrganization($name: String!, $organization: UpdateOrganization!) {
  organizationUpdate(name: $name, organization: $organization) {
    name
    displayName
    description
    creationTimestamp
    lastHeartbeatTime
    admin
    status
    reason
    users {
      name
      isOrganizationAdmin
    }
  }
}

# 删除组织
mutation deleteOrganization($name: String!) {
  organizationDelete(name: $name) {
    code
    status
    reason
    message
  }
}