# 获取节点列表
query getIbppeers($organization: String!) {
  ibppeers(organization: $organization) {
    name
    creationTimestamp
    status
    limits {
      cpu
      memory
    }
    channels
    networks
    pod {
      name
      namespace
      containers
    }
  }
}

# 创建节点
mutation createIbppeer($org: String!, $count: Float) {
  ibppeerCreate(organization: $org, count: $count) {
    name
    creationTimestamp
    status
    limits {
      cpu
      memory
    }
  }
}
