# 获取官方合约列表
query getContracts($lang: Lang){
  contracts(lang: $lang) {
    name
    version
    from
    description
    package
    status
    interfaces {
      name
      args
      description
      condition
    }
  }
}

# 导入官方合约
mutation importContract($name: String!, $network: String!) {
  contractImport(name: $name, network: $network)
}
