# 通道详情
query getChannel($name: String!) {
  channel(name: $name) {
    name
    displayName
    description
    creationTimestamp
    epolicy {
      name
      description
      creationTimestamp
    }
    members {
      name
      joinedAt
    }
    peers {
      name
      namespace
    }
    chaincode {
      name
      displayName
      version
      phase
    }
  }
}

# 创建通道
mutation createChannel($network: String!, $channel: NewChannel!) {
  channelCreate(network: $network, channel: $channel) {
    name
    displayName
    members{
      name
    }
    peers {
      name
      namespace
    }
    creationTimestamp
    status
  }
}

# 更新通道（添加节点）
mutation updateChannel($channel: UpdateChannel!, $name: String!) {
  channelUpdate(channel: $channel, name: $name) {
    name
    displayName
    members{
      name
    }
    peers {
      name
      namespace
    }
    creationTimestamp
    status
  }
}

# 更新通道（邀请组织）
mutation updateMemberChannel($name: String!, $members: [String!]!) {
  channelMemberUpdate(name: $name, members: $members)
}

# 通道中的Admin组织（用户作为admin管理的组织）
query getChannelAdminOrganizations($name: String!) {
  channel(name: $name) {
    name
    adminOrganizations {
      name
      admin
    }
    peers {
      name
      namespace
    }
  }
}

# 获取通道连接文件（针对组织和节点）
query getChannelProfile($name: String!, $organization: String!, $peer: String!) {
  channelProfile(name: $name, organization: $organization, peer: $peer)
}

# 我参与的通道(区块链浏览器)
query getMyChannels{
  channels {
    name
    displayName
    network
    peers {
      name
      namespace
    }
    chaincode {
      name
    }
  }
}
