# 获取提议列表
query getProposals($type: ProposalType) {
  proposals(type: $type) {
    name
    creationTimestamp
    endAt
    type
    policy
    status
    voted
    initiator {
      name
      admin
    }
    votes {
      name
      organizationName
      organizationAdmin
      proposalName
      voteTime
      decision
      description
      status
    }
  }
}

# 获取提议详情
query getProposal($name: String!) {
  proposal(name: $name) {
    name
    creationTimestamp
    endAt
    type
    policy
    status
    voted
    initiator {
      name
      admin
    }
    votes {
      name
      organizationName
      organizationAdmin
      proposalName
      voteTime
      decision
      description
      status
    }
  }
}
