# 获取网络列表
query getNetworks{
  networks {
    name
    creationTimestamp
    lastHeartbeatTime
    expiredTime
    federation
    clusterSize
    ordererType
    organizations {
      name
      admin
    }
    initiator {
      name
    	admin
    }
    status
    channels {
      name
      createdByMe
      iamInvolved
    }
    peers {
      name
      createdByMe
    }
  }
}

# 网络详情
query getNetwork($name: String!) {
  network(name: $name) {
    name
    description
    creationTimestamp
    lastHeartbeatTime
    expiredTime
    federation
    clusterSize
    ordererType
    version
    storage
    limits {
      cpu
      memory
    }
    organizations {
      name
      displayName
      admin
      creationTimestamp
      lastHeartbeatTime
      status
      reason
      ibppeers {
        name
      }
    }
    initiator {
      name
    	admin
    }
    status
    peers {
      name
      createdByMe
    }
    channels {
      name
      members{
        name
      }
      peers {
        name
        namespace
      }
      creationTimestamp
      status
      createdByMe
      iamInvolved
    }
  }
}

# 创建网络
mutation createNetwork($network: NewNetworkInput!) {
  networkCreate(network: $network) {
    name
    creationTimestamp
    lastHeartbeatTime
    expiredTime
    federation
    clusterSize
    ordererType
    status
  }
}

# 释放网络
mutation dissolveNetwork($name: String!, $federation: String!, $initiator: String!) {
  networkDissolve(name: $name, federation: $federation, initiator: $initiator)
}

# 删除网络
mutation deleteNetwork($name: String!) {
  networkDelete(name: $name) {
    code
    status
    message
  }
}